image: python:latest

stages:
  - test
  - creating


Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle KMT_method.py 


Lol_job2:
  stage: test  
  script:
    - python KMT_method.py
    
    

Lol_job3:
 build_image:
   script:
     - docker build -t my-docker-image .
     - docker run my-docker-image /script/to/run/tests



pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - ls
  - pwd
  - sphinx-build -W -b html -c ./ -d {envtmpdir}/doctrees .  {envtmpdir}/html
  - mv {envtmpdir}/html/* ./public/
  - cd ./public/
  - ls
  artifacts:
    paths:
    - public
  only:
  - master
    



    


