image: python:latest

stages:
  - test
  - creating


Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle KMT_method.py 


Lol_job2:
  stage: test  
  script:
    - python KMT_method.py
    
    

  
 before_script:
   - docker info
 build_image:
   stage: creating
   script:
    - docker build -t gr-hlit.jinr.ru/artemev/test-with-python .
    - docker push gr-hlit.jinr.ru/artemev/test-with-python  




pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - ls
  - pwd
  - sphinx-build -W -b html -c ./ -d {envtmpdir}/doctrees .  {envtmpdir}/html
  - mv {envtmpdir}/html/* ./public/
  - cd ./public/
  - ls
  artifacts:
    paths:
    - public
  only:
  - master
    



    


