image: gitlab/dind

services:
  - docker:dind  

stages:
  - creating
  - pagemaking




docker build:
  stage: creating 
  script:

    - docker login gr-hlit.jinr.ru -u $MyPassword -p $MyLogin
    - docker build --help
    - pwd
    - docker build -t MyImage ./builds/artemev/test-with-python/KMT_method.py
    - docker push gr-hlit.jinr.ru/artemev/test-with-python





    



    


