image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - ls
  - pwd
  - sphinx-build -W -b html -c ./ -d {envtmpdir}/doctrees .  {envtmpdir}/html
  - mv {envtmpdir}/html ./public/
  - ls {envtmpdir}/html
  - cd ./public/
  artifacts:
    paths:
    - public
  only:
  - master


    


