image: python:latest

stages:
  - test



Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle *.py


Lol_job2:
  stage: test  
  script:
    - python *.py

