image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - pwd
  - sphinx-build html .
  - pwd
  - mv . public/
  artifacts:
    paths:
    - public
  only:
  - master


    


