image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - pwd
  - sphinx-build html /builds/artemev/test-with-python/All/
  - pwd
  - mv /builds/artemev/test-with-python/All/ public/
  artifacts:
    paths:
    - public
  only:
  - master


    


