image: gitlab/dind

services:
  - docker:dind  

stages:
  - creating
  - pagemaking




docker build:
  stage: creating 
  script:
    - docker login gr-hlit.jinr.ru
    - docker build -t gr-hlit.jinr.ru/artemev/test-with-python .
    - docker push gr-hlit.jinr.ru/artemev/test-with-python





    



    


