  
  stages:
    - test
    - pagemaking
    - creating
    
  Lol_job1:
    stage: test  
    image: python:latest
    script:
      - pip install --upgrade pip
      - pip install pycodestyle
      - pycodestyle KMT_method.py 

  Lol_job2:
    stage: test 
    image: python:latest
    script:
      - python KMT_method.py

  pages:
    stage: pagemaking 
    image: alpine
    script:
      - pip install sphinx
      - sphinx-build -W -b html -c ./ -d {envtmpdir}/doctrees .  {envtmpdir}/html
      - mv {envtmpdir}/html/* ./public/
      - cd ./public/

    artifacts:
      paths:
        - public
    only:
      - master

  docker build:
    stage: creating 
    services:
      - docker:dind  
    image: gitlab/dind  
    script:
      - docker login gr-hlit.jinr.ru -u $MyPassword -p $MyLogin
      - docker build --help
      - docker build -t gr-hlit.jinr.ru/artemev/test-with-python .
      - docker push gr-hlit.jinr.ru/artemev/test-with-python 
      - docker push gr-hlit.jinr.ru/artemev/test-with-python
      



    



    


