image: python:latest

stages:
  - test
  - pages



Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle *.py


Lol_job2:
  stage: test  
  script:
    - python *.py
    
Lol_job3:
  stage: pages  
  script:
    - bash NewMeta.sh
    


