image: python:latest

stages:
  - test
  - pages



Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle *.py


Lol_job2:
  stage: test  
  script:
    - python *.py
    

pages:
  script:
  - pip install -U sphinx
  - sphinx-apidoc -o . .
  - make html
  - cd _build/html/
  artifacts:
    paths:
    - public
  only:
  - master

    


