image: python:latest

stages:
  - test
  - pages



Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle *.py


Lol_job2:
  stage: test  
  script:
    - python *.py
    

pages:
  script:
  - pip install apk
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

    


