image: python:latest

stages:
  - test
  - pages
  - creating


Lol_job1:
  stage: test  
  script:
    - pip install --upgrade pip
    - pip install pycodestyle
    - pycodestyle KMT_method.py 


Lol_job2:
  stage: test  
  script:
    - python KMT_method.py
    



    


